# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d7f7a46c3abffe0486e755f746d1add382d8b079da2948804585fa27b181a71d01985f22f5d40fbac23d95050dddbf02ff352e0f6f5c2f2cf47355df10daa32

test:
  secret_key_base: 96842a216726ff605b73e7c6a94c8d89545332c61dde5542b38109abdb604b26c6dd6fbe732c92f79a2453efa307c403503a1b5cee36cc09ad76bdc6e3049918

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
